name: Black code style check

on: [push]

jobs:
  black:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Install apt dependencies
      run: |
        sudo apt-get update && sudo apt-get install python3 python3-pip -y
    - name: Install pip dependencies
      run: |
        pip3 install black
    - name: Check code style with Black
      run: |
        black --check --diff --line-length 79 .
