name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  publish-python:
    uses: mundialis/github-workflows/.github/workflows/python-publish.yml@python-publish
    # with:
    #   test_pypi: true
    secrets:
      # PYPI_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      PYPI_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Set up Python
  #     uses: actions/setup-python@v4
  #     with:
  #       python-version: '3.x'
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install build wheel setuptools
  #   - name: Build package
  #     run: |
  #       python3 setup.py bdist_wheel
  #   - name: Release
  #     uses: softprops/action-gh-release@v1
  #     if: startsWith(github.ref, 'refs/tags/')
  #     with:
  #       files: dist/*.whl
