name: Upload Python Package

on:
  release:
    types: [published]

# the workflow does not require permissions, but to avoid a code security warning this should be explicitly defined:
permissions: {}

jobs:
  publish-python:
    uses: mundialis/github-workflows/.github/workflows/python-publish.yml@python-publish
    # with:
    #   test_pypi: true
    secrets:
      # PYPI_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      PYPI_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
