name: Python code quality check

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:

  tests:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Start containers
      run: docker-compose -f "docker/docker-compose-test.yml" up -d --build
    - name: List running docker
      run: docker ps
    - name: Running tests
      run: make test
    - name: Stop containers
      run: docker-compose -f "docker/docker-compose-test.yml" down

  mocked-tests:
￼    runs-on: ubuntu-20.04
￼    steps:
￼    - uses: actions/checkout@v2
￼    - name: Set up Python
￼      uses: actions/setup-python@v2
￼      with:
￼        python-version: 3.8
￼    - name: Install
￼      run: |
￼        python -m pip install --upgrade pip
￼    - name: Run Tests
￼      run: |
￼        make mockedtest
