name: Generate Third-Party Licenses

on:
  release:
    types: [published]

permissions: {}

jobs:
  generate-third-party-licenses:
    uses: mundialis/github-workflows/.github/workflows/third-party-licenses.yml@main
    with:
      pyproject: pyproject.toml
