#!/usr/bin/env python
# -*- coding: utf-8 -*-
#######
# acintia-python-client is a python client for actinia - an open source REST
# API for scalable, distributed, high performance processing of geographical
# data that uses GRASS GIS for computational tasks.
#
# Copyright (c) 2022 mundialis GmbH & Co. KG
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#######

__license__ = "GPLv3"
__author__ = "Anika Weinmann"
__copyright__ = "Copyright 2022, mundialis GmbH & Co. KG"
__maintainer__ = "Anika Weinmann"

from .actinia_mock import (
    ACTINIA_BASEURL,
    ACTINIA_VERSION,
    # fill_basic_frame,
)


get_rasters_mock = {
    "accept_datetime": "2022-06-13 13:04:53.422064",
    "accept_timestamp": 1655125493.4220603,
    "api_info": {
        "endpoint": "rasterlayersresource",
        "method": "GET",
        "path": f"/api/{ACTINIA_VERSION}/locations/nc_spm_08/mapsets/"
        "PERMANENT/raster_layers",
        "request_url": f"{ACTINIA_BASEURL}/api/{ACTINIA_VERSION}/locations/"
        "nc_spm_08/mapsets/PERMANENT/raster_layers",
    },
    "datetime": "2022-06-13 13:04:53.740702",
    "http_code": 200,
    "message": "Processing successfully finished",
    "process_chain_list": [
        {
            "1": {
                "inputs": {"mapset": "PERMANENT", "type": "raster"},
                "module": "g.list",
            }
        }
    ],
    "process_log": [
        {
            "executable": "g.list",
            "id": "1",
            "parameter": ["mapset=PERMANENT", "type=raster"],
            "return_code": 0,
            "run_time": 0.10059475898742676,
            "stderr": [""],
            "stdout": "aspect\nbasin_50K\nboundary_county_500m\ncfactorbare_"
            "1m\ncfactorgrow_1m\nel_D782_6m\nel_D783_6m\nel_D792_6m\nel_D793_"
            "6m\nelev_lid792_1m\nelev_ned_30m\nelev_srtm_30m\nelev_state_500"
            "m\nelevation\nelevation_shade\nfacility\ngeology_30m\nlakes"
            "\nlandclass96\nlandcover_1m\nlanduse96_28m\nlsat7_2002_10\n"
            "lsat7_2002_20\nlsat7_2002_30\nlsat7_2002_40\nlsat7_2002_50\n"
            "lsat7_2002_61\nlsat7_2002_62\nlsat7_2002_70\nlsat7_2002_80"
            "\nncmask_500m\northo_2001_t792_1m\nroadsmajor\nslope\nsoilsID\n"
            "soils_Kfactor\nstreams_derived\ntowns\nurban\nzipcodes\n"
            "zipcodes_dbl\n",
        }
    ],
    "process_results": [
        "aspect",
        "basin_50K",
        "boundary_county_500m",
        "cfactorbare_1m",
        "cfactorgrow_1m",
        "el_D782_6m",
        "el_D783_6m",
        "el_D792_6m",
        "el_D793_6m",
        "elev_lid792_1m",
        "elev_ned_30m",
        "elev_srtm_30m",
        "elev_state_500m",
        "elevation",
        "elevation_shade",
        "facility",
        "geology_30m",
        "lakes",
        "landclass96",
        "landcover_1m",
        "landuse96_28m",
        "lsat7_2002_10",
        "lsat7_2002_20",
        "lsat7_2002_30",
        "lsat7_2002_40",
        "lsat7_2002_50",
        "lsat7_2002_61",
        "lsat7_2002_62",
        "lsat7_2002_70",
        "lsat7_2002_80",
        "ncmask_500m",
        "ortho_2001_t792_1m",
        "roadsmajor",
        "slope",
        "soilsID",
        "soils_Kfactor",
        "streams_derived",
        "towns",
        "urban",
        "zipcodes",
        "zipcodes_dbl",
    ],
    "progress": {"num_of_steps": 1, "step": 1},
    "resource_id": "resource_id-0a7cb1ed-4fab-4353-9aac-87bb292c5a48",
    "status": "finished",
    "time_delta": 0.31871747970581055,
    "timestamp": 1655125493.7406285,
    "urls": {
        "resources": [],
        "status": f"{ACTINIA_BASEURL}/api/{ACTINIA_VERSION}/resources/anika/"
        "resource_id-0a7cb1ed-4fab-4353-9aac-87bb292c5a48",
    },
    "user_id": "anika",
}

raster_info_resp = {
    "cells": "2025000",
    "cols": "1500",
    "comments": '"int(zipcodes)"',
    "creator": '"helena"',
    "database": "/actinia_core/workspace/temp_db/"
                "gisdbase_d6bc2ddef1fd4471a84261ea5b108417",
    "datatype": "CELL",
    "date": '"Sun Jan 14 22:36:04 2007"',
    "description": '"generated by r.mapcalc"',
    "east": "645000",
    "ewres": "10",
    "location": "nc_spm_08",
    "map": "zipcodes",
    "mapset": "PERMANENT",
    "maptype": "raster",
    "max": "27610",
    "min": "27511",
    "ncats": "27610",
    "north": "228500",
    "nsres": "10",
    "rows": "1350",
    "semantic_label": '"none"',
    "source1": '""',
    "source2": '""',
    "south": "215000",
    "timestamp": '"none"',
    "title": '"South West Wake: Zipcode areas derived from vector map"',
    "units": '"none"',
    "vdatum": '"none"',
    "west": "630000",
}


get_raster_info_mock = {
    "accept_datetime": "2022-06-13 13:28:23.934771",
    "accept_timestamp": 1655126903.934769,
    "api_info": {
        "endpoint": "rasterlayerresource",
        "method": "GET",
        "path": f"/api/{ACTINIA_VERSION}/locations/nc_spm_08/mapsets/PERMANENT"
                "/raster_layers/zipcodes",
        "request_url": f"{ACTINIA_BASEURL}/api/{ACTINIA_VERSION}/locations/"
                       "nc_spm_08/mapsets/PERMANENT/raster_layers/zipcodes",
    },
    "datetime": "2022-06-13 13:28:24.685413",
    "http_code": 200,
    "message": "Processing successfully finished",
    "process_chain_list": [
        {
            "1": {
                "flags": "gre",
                "inputs": {"map": "zipcodes@PERMANENT"},
                "module": "r.info",
            }
        }
    ],
    "process_log": [
        {
            "executable": "r.info",
            "id": "1",
            "mapset_size": 421,
            "parameter": ["map=zipcodes@PERMANENT", "-gre"],
            "return_code": 0,
            "run_time": 0.1002960205078125,
            "stderr": [""],
            "stdout": 'north=228500\nsouth=215000\neast=645000\nwest=630000'
            '\nnsres=10\newres=10\nrows=1350\ncols=1500\ncells=2025000\n'
            'datatype=CELL\nncats=27610\nmin=27511\nmax=27610\nmap=zipcodes\n'
            'maptype=raster\nmapset=PERMANENT\nlocation=nc_spm_08\ndatabase'
            '=/actinia_core/workspace/temp_db/gisdbase_d6bc2ddef1fd4471a8426'
            '1ea5b108417\ndate="Sun Jan 14 22:36:04 2007"\ncreator="helena"\n'
            'title="South West Wake: Zipcode areas derived from vector map"\n'
            'timestamp="none"\nunits="none"\nvdatum="none"\nsemantic_label='
            '"none"\nsource1=""\nsource2=""\ndescription="generated by '
            'r.mapcalc"\ncomments="int(zipcodes)"\n',
        }
    ],
    "process_results": raster_info_resp,
    "progress": {"num_of_steps": 1, "step": 1},
    "resource_id": "resource_id-165e9eca-9ab1-488b-8f49-d8b61f02315c",
    "status": "finished",
    "time_delta": 0.7506742477416992,
    "timestamp": 1655126904.6853848,
    "urls": {
        "resources": [],
        "status": f"{ACTINIA_BASEURL}/api/{ACTINIA_VERSION}/resources/anika/"
                  "resource_id-165e9eca-9ab1-488b-8f49-d8b61f02315c",
    },
    "user_id": "anika",
}
